[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nexus"
version = "0.1.0"
description = "Asistente de terminal"
readme = "README.md"
requires-python = ">=3.10"

# Dependencias (las pones aquí si quieres que se instalen automáticamente)
dependencies = [
    "cerebras_cloud_sdk",
    "groq", 
    "google-genai", 
    "python-dotenv", 
    "rich", 
    "pyperclip"
]

[project.scripts]
# Esto crea el comando "nexus" en la terminal
nexus = "nexus.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["nexus*"]
